Repository elastos/Elastos.ELA, pull requests merged in 2019-01, with the labels that each got.

#613 fix channel dead lock in dpos store
  dpos/network.go
  dpos/store/arbitratorsstore.go
  dpos/store/dposstore.go
  dpos/store/eventstore.go
Labels: ct-BugFix

#614 disable unit and whitebox test temporarily
  .travis.yml
Labels: ct-BuildChanges

#615 fix inactive arbitrators processing error when block height is lower …
  blockchain/blockchain.go
Labels: ct-BugFix

#617 initialize LocalPow before start rpc server
  main.go
Labels: ct-BugFix

#618 fix foundation address initialization
  config.go
  main.go
  version/blocks/blockv0.go
Labels: ct-BugFix

#616 implement concurrent recursive call detect for events.go
  common/common.go
  events/events.go
  events/events_test.go
Labels: ct-BehaviorChanges

#619 implement STAT log to print out peer-to-peer state per minute
  common/log/log.go
  main.go
Labels: ct-NewFeature

#623 fix CRC configuration ineffectiveness error
  common/config/config.go
  common/config/params.go
  config.go
  config.json.sample
Labels: ct-BugFix

#628 change peer last active timeout from 10 minutes to 1 minute
  node/node.go
Labels: ct-BugFix

#629 add rpc interface to get deposit coin information
  blockchain/validation_test.go
  crypto/encode.go
  docs/jsonrpc_apis.md
  servers/httpjsonrpc/server.go
  servers/interfaces.go
Labels: ct-RPC
