Repository elastos/Elastos.ELA, pull requests merged in 2019-07, with the labels that each got.

#1038 Reduce Hub pipe buffer from 1MB to 1KB
  dpos/p2p/hub/hub.go
Labels: ct-BugFix

#1056 Improve file permissions security
  account/fileStore.go
  cmd/common/common.go
  cmd/wallet/common.go
  dpos/p2p/addrmgr/addrmanager.go
  p2p/addrmgr/addrmanager.go
  utils/elalog/filewriter.go
Labels: security

#1081 implement cr candidates related
  cr/state/candidate.go
  cr/state/candidate_test.go
  cr/state/checkpoint.go
  cr/state/checkpoint_test.go
  cr/state/state.go
  cr/state/state_test.go
  dpos/state/checkpoint.go
  utils/common.go
Labels: ct-NewFeature

#1077 add log to show block infomation when check failed
  blockchain/blockvalidator.go
  dpos/state/state.go
Labels: ct-NewFeature

#1076 check block context before appending to blockpool
  blockchain/blockchain.go
  blockchain/blockvalidator.go
  mempool/blockpool.go
Labels: ct-BehaviorChanges
