Repository elastos/Elastos.ELA, pull requests merged in 2019-05, with the labels that each got.

#932 fix inactive arbiter when timeout after update next arbiters
  dpos/manager/viewchangescountdown.go
  dpos/state/arbitrators.go
Labels: ct-BugFix

#933 fix check withdraw transaction failed error
  blockchain/txvalidator.go
  blockchain/validation.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/interface.go
Labels: ct-BugFix

#936 Fix node fall to no neighbors issue
  elanet/dns/dns_test.go
  elanet/dns/main/main.go
  elanet/netsync/manager.go
  log.go
  p2p/connmgr/connmanager.go
  p2p/server/server.go
Labels: ct-BugFix

#934 add --datadir and --conf flags for ela
  .gitignore
  Makefile
  blockchain/blockvalidator_test.go
  blockchain/chainstore_test.go
  blockchain/mediantime_test.go
  blockchain/txvalidator_specailtx_test.go
  blockchain/txvalidator_test.go
  cmd/common/common.go
  cmd/common/flags.go
  cmd/config.go
  cmd/ela-cli.go
  cmd/script/api/api.go
  cmd/wallet/account.go
  cmd/wallet/flags.go
  cmd/wallet/transaction.go
  cmd/wallet/txbuilder.go
  common/log/log.go
  config.go
  docs/config.json.md
  dpos/store/eventstore_test.go
  log.go
  main.go
  mempool/txpool_test.go
  pow/service_test.go
  util.sh
  utils/password.go
  utils/test/test.go
Labels: ct-NewFeature

#937 fix cli no-change bug
  cmd/wallet/common.go
  cmd/wallet/txbuilder.go
  servers/interfaces.go
Labels: ct-BugFix

#922 Implement DNS seeds to replace of seed list
  common/config/config.go
  common/config/params.go
  config.go
  config.json.sample
  docs/config.json.md
  elanet/server.go
  main.go
  p2p/addrmgr/addrmanager.go
  p2p/server/config.go
  p2p/server/seed.go
  p2p/server/server.go
Labels: ct-BehaviorChanges, ct-ConfigChanges

#939 allow activate producer in next block
  blockchain/txvalidator.go
  dpos/state/arbitrators.go
Labels: ct-BehaviorChanges

#941 Fix DPoS lost connect for dynamic IP
  config.go
Labels: ct-BugFix

#946 Advertise localhost when outbound connected
  dpos/arbitrator.go
  dpos/network.go
  dpos/p2p/addrmgr/addrmanager.go
  dpos/p2p/config.go
  dpos/p2p/msg/addr.go
  dpos/p2p/msg/commands.go
  dpos/p2p/msg/empty.go
  dpos/p2p/peer/peer.go
  dpos/p2p/server.go
  elanet/routes/routes.go
  main.go
Labels: ct-BugFix

#948 fix cancel producer error
  dpos/state/state.go
Labels: ct-BugFix

#947 Enable RPC service through config
  common/config/config.go
  config.json.sample
  docs/config.json.md
  docs/mainnet_config.json.sample
  docs/testnet_config.json.sample
  main.go
Labels: ct-ConfigChanges

#949 add datapath for dpos p2p server
  dpos/network.go
Labels: ct-BugFix

#950 calculate transactions fee in block when InitProducerState
  blockchain/blockchain.go
Labels: ct-BugFix

#952 fix calculateTxsFee failed error
  blockchain/blockchain.go
Labels: ct-BugFix

#953 fix producer related tx record even if tx has double spent
  mempool/txpool.go
Labels: ct-BugFix

#951 Specify magic number of DNS service
  .travis.yml
  elanet/dns/README.md
  elanet/dns/main/main.go
Labels: ct-NewFeature

#955 fix check coinbase reward amount failed error
  blockchain/blockchain.go
  blockchain/confirmvalidator.go
Labels: ct-BugFix

#956 fix pre process inactive tx when InitProducerState error
  blockchain/blockchain.go
  blockchain/confirmvalidator.go
  dpos/state/arbitrators.go
Labels: ct-BugFix

#958 fix error that tx pool would not clear some tx that input length is 0
  mempool/txpool.go
Labels: ct-BugFix

#960 fix error that sidechain, updateversion and activateproducer tx can't…
  mempool/txpool.go
Labels: ct-BugFix

#962 fix processVoteOutput failed error
  blockchain/txvalidator.go
  dpos/state/state.go
Labels: ct-BugFix

#963 revert the help rpc interface
  servers/httpjsonrpc/server.go
  servers/interfaces.go
Labels: ct-RPC

#964 fix process vote output error
  dpos/state/state.go
Labels: ct-BugFix

#965 change inactive tx creating and checking strategy
  blockchain/txvalidator.go
  blockchain/txvalidator_specailtx_test.go
  dpos/manager/dposondutyhandler.go
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#966 fix error that producer will recover from inactive state automaticall…
  dpos/state/state.go
Labels: ct-BugFix

#967 modify listproducers function to get different type of producers
  docs/jsonrpc_apis.md
  dpos/state/state.go
  servers/interfaces.go
Labels: ct-RPC

#970 fix update progam hashes error if there are current arbiters changed …
  dpos/state/arbitrators.go
Labels: ct-BugFix

#969 Fix routes address announce deadlock issue
  elanet/routes/routes.go
  elanet/routes/routes_test.go
Labels: ct-BugFix

#971 Fix routes do not announce address on startup
  elanet/routes/routes.go
  elanet/routes/routes_test.go
Labels: ct-BugFix

#973 Fix peers stall timeout on startup issue
  elanet/peer/peer.go
Labels: ct-BugFix

#978 fix forthchange when InitProducerState error
  blockchain/txvalidator_test.go
  cmd/script/api/api.go
  dpos/state/arbitrators.go
  dpos/state/heightversion_test.go
  main.go
Labels: ct-BugFix

#975 Fix handle message null pointer panic issue
  dpos/p2p/peer/peer.go
  dpos/p2p/server.go
Labels: ct-BugFix

#979 Re-announce address when DPoS network go bad
  dpos/arbitrator.go
  dpos/manager/dposmanager.go
  dpos/network.go
  elanet/routes/routes.go
  elanet/routes/routes_test.go
  main.go
Labels: ct-BugFix

#976 all float reward should use math floor to truncate the fractional part
  dpos/state/arbitrators.go
Labels: ct-BugFix

#980 fix recover abnormal state error
  dpos/arbitrator.go
  dpos/manager/dposmanager.go
  dpos/manager/proposaldispatcher.go
  dpos/manager/view.go
Labels: ct-BugFix

#982 Fix routes concurrent map writes panic
  elanet/routes/routes.go
Labels: ct-BugFix

#983 record proposals that are greater than current view offset and process later
  dpos/manager/dposhandlerswitch.go
  dpos/manager/illegalbehaviormonitor.go
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#984 Fix DPoS reconnect to non-producer peers issue
  dpos/p2p/connmgr/connmanager.go
  dpos/p2p/server.go
Labels: ct-BugFix

#986 check publickey by different height when register or update producer
  blockchain/txvalidator.go
Labels: ct-BugFix

#987 not call recover when receiving the same or pending proposal
  dpos/manager/dposmanager.go
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#988 Fix routes QueueInv deadlock issue
  elanet/peer/peer.go
  elanet/routes/routes.go
  elanet/routes/routes_test.go
Labels: ct-BugFix

#990 distribution of dpos reward to crc by check count of current arbitrators
  dpos/state/arbitrators.go
Labels: ct-BugFix

#992 update peers only when producer is the peer need to be connected
  dpos/network.go
Labels: ct-BugFix

#994 fix build error after merge commits
  dpos/state/arbitrators.go
Labels: ct-BugFix

#996 fix activate tx did not clean related node public key error
  mempool/txpool.go
Labels: ct-BugFix

#998 distribute dpos reward by current votes of producers
  dpos/state/arbitrators.go
Labels: ct-BugFix

#997 Fix routes can not update peers on start
  elanet/routes/routes.go
Labels: ct-BugFix

#999 Fix hub pipe buffer cause out of memory issue
  dpos/p2p/hub/hub.go
Labels: ct-BugFix

#1000 fix error that node may process special tx even during sync
  blockchain/blockchain.go
Labels: ct-BugFix

#1001 do not reset view offset if degration happens
  dpos/manager/dposmanager.go
  dpos/manager/illegalbehaviormonitor.go
  dpos/manager/proposaldispatcher.go
  dpos/manager/viewchangescountdown.go
Labels: ct-BugFix

#1002 fix process special transaction when initializing producer state error
  blockchain/confirmvalidator.go
Labels: ct-BugFix

#1003 support kill pid to exit procedure
  utils/signal/interrupt.go
Labels: ct-BugFix

#1006 fix crc timeout lead to consensus failed error
  dpos/manager/proposaldispatcher.go
  dpos/manager/viewchangescountdown.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/interface.go
Labels: ct-BugFix

#1008 only record proposal send by sponsor for producer state recovery
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#1004 Fix hub disconnect after first message issue
  dpos/p2p/hub/hub.go
  dpos/p2p/hub/hub_test.go
Labels: ct-BugFix

#1007 Fix DPoS reconnect to non-producer peers issue
  dpos/p2p/connmgr/connmanager.go
  dpos/p2p/server.go
Labels: ct-BugFix

#1005 check if block in store by get block header
  blockchain/chainstore.go
Labels: ct-BugFix

#1011 Do not block queue when GetData no response
  elanet/routes/routes.go
  elanet/routes/routes_test.go
  elanet/server.go
Labels: ct-BugFix

#1013 fix check vote prodcuer transaction failed error before PublicDPOSHeight
  blockchain/txvalidator.go
  dpos/state/state.go
Labels: ct-BugFix

#1016 Fix DPoS ConnManager can not reconnect issue
  dpos/p2p/connmgr/connmanager.go
  dpos/p2p/server.go
Labels: ct-BugFix

#1014 fix reward calculate error at H2 height
  dpos/state/arbitrators.go
Labels: ct-BugFix

#1020 fix PendingCanceledProducers not initialized error
  dpos/state/state.go
  dpos/store/arbitratorsstore_test.go
Labels: ct-BugFix

#1022 fix get candidates error when update next arbiters
  dpos/state/arbitrators.go
Labels: ct-BugFix

#1023 not request blocks when received lastblock
  elanet/netsync/manager.go
Labels: ct-BugFix

#1018 Limit non-node peer connections to 100
  elanet/server.go
Labels: ct-BehaviorChanges

#981 Improve code cleanup duplicate code
  dpos/state/arbitrators.go
Labels: ct-BugFix

#1021 Remove ConnReq from pending when failed
  p2p/connmgr/connmanager.go
  p2p/connmgr/connmanager_test.go
  p2p/peer/peer.go
Labels: ct-BugFix

#1028 only clean blocks that are lower than current block when start consensus
  dpos/manager/consensus.go
  dpos/manager/consensusblockcache.go
  dpos/manager/dposmanager.go
Labels: ct-BugFix

#1029 let illegal related tx order by bytes instead of string
  blockchain/txvalidator.go
  blockchain/txvalidator_specailtx_test.go
  cmd/script/api/illegalproposals.go
  cmd/script/api/illegalvotes.go
  dpos/manager/illegalbehaviormonitor.go
  mempool/blockevidence.go
Labels: ct-BugFix

#1032 fix rollback before VoteStartHeight lead to disconnect block failed e…
  blockchain/blockchain.go
Labels: ct-BugFix

#1031 process block ignore whether processing block exist
  dpos/manager/dposhandlerswitch.go
  dpos/manager/dposondutyhandler.go
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix
