Repository elastos/Elastos.ELA, pull requests merged in 2019-02, with the labels that each got.

#639 fix all unit tests
  .travis.yml
  blockchain/blockvalidator_test.go
  blockchain/chainstore_test.go
  blockchain/chainstoremock.go
  blockchain/mock/arbitratorsmock.go
  blockchain/mock/blockheightmock.go
  blockchain/mock/heightversionsmock.go
  blockchain/txvalidator.go
  blockchain/txvalidator_test.go
  blockchain/validation_test.go
  cmd/config.go
  common/config/template.go
  config.go
  core/types/transaction_test.go
  dpos/p2p/peer/peer_test.go
  dpos/state/state_test.go
  dpos/store/eventstore_test.go
  mempool/txpool_test.go
  p2p/peer/peer_test.go
  version/blocks/blocks_test.go
  version/blocks/blockv0_test.go
  version/heights/heights_test.go
  version/txs/txv0_test.go
  version/txs/txv1_test.go
  version/txs/txv2_test.go
Labels: ct-ConfigChanges

#638 Add NAFilter parameter into server config
  p2p/server/config.go
  p2p/server/server.go
Labels: ct-NewFeature

#640 fix all white box test
  .travis.yml
  cmd/script/api/api.go
  cmd/script/api/dposmanager.go
  cmd/script/api/dposnetwork.go
  cmd/script/api/mock/dposnetwork.go
  common/config/template.go
  dpos/manager/proposaldispatcher.go
  test/common/test_utils.lua
  test/white_box/dpos/illegal_proposals.lua
  test/white_box/dpos/normal_one_view_success.lua
  test/white_box/dpos/onduty_one_view_success.lua
  test/white_box/main/test_all.lua
Labels: ct-ConfigChanges

#637 Revert "Add filterack message to response to filterload message"
  node/handlereip001.go
  p2p/message.go
  p2p/msg/filterack.go
Labels: ct-Revert

#627 Do not add useless addresses into AddrManager
  p2p/addrmgr/addrmanager.go
  p2p/msg/version.go
  p2p/nafilter.go
  p2p/peer/peer.go
  p2p/server/server.go
Labels: ct-BugFix

#643 fix network address filter not working issue
  p2p/server/server.go
Labels: ct-BugFix

#624 fix ConnManager not make target connections issue
  p2p/connmgr/connmanager.go
  p2p/connmgr/connmanager_test.go
Labels: ct-BugFix

#644 Arrange dpos related definitions
  blockchain/blockchain.go
  blockchain/chaindata.go
  blockchain/chainstore.go
  blockchain/confirmvalidator.go
  blockchain/ledgerstore.go
  blockchain/mock/arbitratorsmock.go
  blockchain/txvalidator.go
  cmd/script/api/confirm.go
  cmd/script/api/dposmanager.go
  cmd/script/api/iilegalproposals.go
  cmd/script/api/illegalblocks.go
  cmd/script/api/illegalvotes.go
  cmd/script/api/mock/dposnetwork.go
  cmd/script/api/proposal.go
  cmd/script/api/vote.go
  core/types/dposblock.go
  core/types/dposillegalproposals.go
  core/types/payload/confirm.go
  core/types/payload/dposillegalblocks.go
  core/types/payload/dposillegaldata.go
  core/types/payload/dposillegalproposals.go
  core/types/payload/dposillegalvotes.go
  core/types/payload/dposproposal.go
  core/types/payload/dposproposalvote.go
  core/types/payload/sidechainillegaldata.go
  core/types/payloadillegalblock.go
  core/types/payloadillegalproposal.go
  core/types/payloadillegalvote.go
  core/types/payloadsidechainillegaldata.go
  core/types/transaction.go
  core/types/transaction_test.go
  dpos/account/dposaccount.go
  dpos/arbitrator.go
  dpos/manager/consensusblockcache.go
  dpos/manager/dposhandlerswitch.go
  dpos/manager/dposmanager.go
  dpos/manager/dposnormalhandler.go
  dpos/manager/dposondutyhandler.go
  dpos/manager/evidencecache.go
  dpos/manager/illegalbehaviormonitor.go
  dpos/manager/proposaldispatcher.go
  dpos/network.go
  dpos/p2p/msg/consensusstatus.go
  dpos/p2p/msg/illegalproposals.go
  dpos/p2p/msg/illegalvotes.go
  dpos/p2p/msg/proposal.go
  dpos/p2p/msg/sidechainillegaldata.go
  dpos/p2p/msg/vote.go
  dpos/state/state.go
  dpos/state/state_test.go
  dpos/store/arbitrators.go
  dpos/store/eventstore.go
  dpos/store/eventstore_test.go
  elanet/netsync/manager.go
  mempool/blockpool.go
  servers/interfaces.go
  version/blocks/blockv1.go
Labels: ct-Refactor

#648 reject the block which have existing height
  servers/interfaces.go
Labels: ct-BugFix

#645 Move NAFilter from peer to AddrManager
  node/handlerbase.go
  p2p/addrmgr/addrmanager.go
  p2p/addrmgr/addrmanager_test.go
  p2p/peer/peer.go
  p2p/server/server.go
Labels: ct-BugFix

#650 fix AddrManager savePeers() get panic issue
  p2p/addrmgr/addrmanager.go
  p2p/addrmgr/addrmanager_test.go
Labels: ct-BugFix

#651 make sure producer can return deposit once and can not overspend
  blockchain/txvalidator.go
  dpos/state/state.go
Labels: ct-NewFeature

#652 Update glide.yaml
  glide.yaml
Labels: ct-BuildChanges

#660 let arbiter init from memory state instead of from database
  blockchain/interfaces/arbitrators.go
  blockchain/interfaces/dposstore.go
  blockchain/interfaces/heightversions.go
  blockchain/mock/arbitratorsmock.go
  blockchain/txvalidator.go
  blockchain/txvalidator_test.go
  cmd/script/api/api.go
  dpos/arbitrator.go
  dpos/state/arbitrators.go
  dpos/state/state.go
  dpos/state/state_test.go
  dpos/store/arbitratorsstore.go
  main.go
  servers/httpjsonrpc/server.go
  servers/interfaces.go
  version/version.go
Labels: ct-Refactor

#662 remove unused process block message
  elanet/netsync/manager.go
Labels: ct-Refactor

#667 fix log panic error
  dpos/state/state.go
Labels: ct-BugFix

#668 let arbitrators always beyond one block
  blockchain/confirmvalidator.go
  blockchain/interfaces/arbitrators.go
  blockchain/mock/arbitratorsmock.go
  dpos/network.go
  dpos/state/arbitrators.go
  dpos/state/state.go
  version/blocks/blockv1.go
  version/txs/txv2.go
Labels: ct-BugFix

#669 change to dpos arbiters when received block equal dpos height-1
  blockchain/blockchain.go
  dpos/arbitrator.go
  dpos/manager/dposmanager.go
  dpos/network.go
  dpos/state/arbitrators.go
  dpos/state/state.go
  version/blocks/blockv0.go
Labels: ct-BugFix

#655 fix AddrManager loadPeers() get panic issue
  p2p/addrmgr/addrmanager.go
  p2p/addrmgr/addrmanager_test.go
Labels: ct-BugFix

#676 fix mining errors
  version/blocks/blockv1.go
  version/txs/txv2_test.go
  version/txs/txv3.go
  version/txs/txv3_test.go
  version/version.go
Labels: ct-BugFix

#674 Rename SFOpenNode to SFNodeBloom
  elanet/pact/protocol.go
  elanet/server.go
Labels: ct-Refactor

#671 chg http return code
  servers/httpjsonrpc/server.go
Labels: ct-BugFix

#679 modify to active producer by 6 confirms
  dpos/state/state.go
  dpos/state/state_test.go
Labels: ct-BugFix

#680 fix get normal arbiters and candidates error
  dpos/p2p/msg/consensusstatus.go
  dpos/state/arbitrators.go
Labels: ct-BugFix

#682 Fix same proposal arrived multi-times will cause illegal proposal error
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#685 fix illegal tx check errors
  blockchain/txvalidator.go
  dpos/manager/evidencecache.go
Labels: ct-BugFix

#687 fix get onduty arbiter error and add check for proposal
  blockchain/confirmvalidator.go
  blockchain/interfaces/arbitrators.go
  blockchain/mock/arbitratorsmock.go
  dpos/arbitrator.go
  dpos/manager/proposaldispatcher.go
  dpos/state/arbitrators.go
  dpos/state/state.go
Labels: ct-BugFix

#686 implement DumpPeersInfo() interface for dpos/server
  dpos/p2p/interface.go
  dpos/p2p/server.go
  dpos/p2p/server_test.go
Labels: ct-NewFeature
