Repository elastos/Elastos.ELA, pull requests merged in 2019-03, with the labels that each got.

#691 Disconnect full node peers that do not support DPOS
  elanet/pact/protocol.go
  elanet/peer/peer.go
  elanet/server.go
Labels: ct-MetaData

#692 modify rpc interface about getting dpos peers information
  docs/jsonrpc_apis.md
  dpos/arbitrator.go
  servers/httpjsonrpc/server.go
  servers/interfaces.go
Labels: ct-RPC

#706 separate tx version from height version
  blockchain/interfaces/heightversions.go
  blockchain/mock/heightversionsmock.go
  blockchain/txvalidator.go
  blockchain/txvalidator_test.go
  version/heights/heights.go
  version/heights/heights_test.go
  version/txs/txs.go
  version/txs/txv0.go
  version/txs/txv0_test.go
  version/txs/txv1.go
  version/txs/txv1_test.go
  version/txs/txv2.go
  version/txs/txv2_test.go
  version/txs/txv3_test.go
  version/version.go
Labels: ct-Refactor

#705 remove the tx type restrict about deposit address
  blockchain/txvalidator.go
Labels: ct-BehaviorChanges

#708 Remove ELA.Utility from glide.yaml
  glide.yaml
Labels: ct-ConfigChanges

#716 fix getdpospeersinfo restful interface error
  servers/interfaces.go
Labels: ct-BugFix

#715 arrange lua white box framework
  blockchain/mock/arbitratorsmock.go
  cmd/script/api/api.go
  cmd/script/api/arbitrators.go
  cmd/script/api/block.go
  cmd/script/api/dposmanager.go
  cmd/script/api/header.go
  cmd/script/api/mock/peer.go
  cmd/script/api/proposal.go
  cmd/script/api/txtype.go
  dpos/manager/dposmanager.go
  test/white_box/block_utils.lua
  test/white_box/confirm_suite.lua
  test/white_box/dpos/illegal_proposals.lua
  test/white_box/dpos/normal_one_view_success.lua
  test/white_box/dpos/onduty_one_view_success.lua
  test/white_box/dpos_manager.lua
  test/white_box/dpos_test_suite.lua
  test/white_box/log_config.lua
Labels: ct-Refactor

#719 panic when count of arbiters less than minimum
  dpos/state/arbitrators.go
  version/blocks/blockv2.go
Labels: ct-BugFix

#714 change rollback argument format
  cmd/rollback/rollback.go
Labels: ct-CliChanges

#720 Fix CRC arbiters not registered into dpos/state issue
  dpos/state/arbitrators.go
  dpos/state/state.go
  main.go
Labels: ct-BugFix

#721 fix bugs and show arbiters informations
  dpos/network.go
  dpos/state/arbitrators.go
  dpos/state/log.go
  dpos/state/state.go
  log.go
  mempool/blockpool.go
  version/blocks/blockv2.go
Labels: ct-BugFix

#703 Implement InstantBlock() for network parameters
  blockchain/blockvalidator_test.go
  blockchain/chainstore_test.go
  blockchain/interfaces/arbitrators.go
  blockchain/mock/arbitratorsmock.go
  blockchain/txvalidator_test.go
  cmd/config.go
  cmd/script/api/api.go
  common/config/config.go
  common/config/params.go
  common/config/template.go
  config.go
  config.json.sample
  docs/config.json.md
  docs/mainnet_config.json.sample
  docs/testnet_config.json.sample
  dpos/state/arbitrators.go
  dpos/state/state_test.go
  mempool/txpool_test.go
  servers/httpwebsocket/server.go
  version/blocks/blocks_test.go
  version/blocks/blockv0_test.go
  version/txs/txv0_test.go
  version/txs/txv1_test.go
  version/txs/txv2_test.go
  version/txs/txv3_test.go
Labels: ct-ConfigChanges

#725 separate version package from state package
  blockchain/interfaces/heightversions.go
  dpos/state/arbitrators.go
  dpos/state/heightversion.go
  dpos/state/heightversion_test.go
  dpos/state/state.go
  version/blocks/blocks.go
  version/blocks/blockv0.go
  version/blocks/blockv0_test.go
  version/blocks/blockv2.go
  version/heights/heights.go
Labels: ct-Refactor

#726 check illegal payload when receiving
  blockchain/txvalidator.go
  dpos/arbitrator.go
  dpos/manager/dposmanager.go
  dpos/manager/proposaldispatcher.go
  version/blocks/blockv1.go
Labels: ct-BugFix

#723 send illegal blocks tx only when view offset is equal, and restrict r…
  blockchain/blockchain.go
  blockchain/txvalidator.go
  core/types/payload/dposillegalblocks.go
  core/types/transaction_test.go
  version/blocks/blockv1.go
Labels: ct-BehaviorChanges

#724 Remove Payload prefix for classes in types/payload package
  core/types/payload/coinbase.go
  core/types/payload/dposillegalblocks.go
  core/types/payload/dposillegalproposals.go
  core/types/payload/dposillegalvotes.go
  core/types/payload/inactivearbitrators.go
  core/types/payload/record.go
  core/types/payload/registerproducer.go
  core/types/payload/sidechainillegaldata.go
  core/types/payload/sidechainpow.go
  core/types/payload/updateproducer.go
  dpos/manager/illegalbehaviormonitor.go
  dpos/manager/proposaldispatcher.go
  dpos/p2p/msg/illegalproposals.go
  dpos/p2p/msg/illegalvotes.go
  dpos/p2p/msg/sidechainillegaldata.go
  servers/interfaces.go
  version/blocks/blockv1.go
Labels: ct-Refactor

#729 add rollback document, and fix spell mistake
  cmd/rollback/rollback.go
  docs/cli_user_guide_CN.md
Labels: ct-AddComments

#732 fix white box check error
  cmd/script/api/api.go
  cmd/script/api/block.go
  cmd/script/api/dposmanager.go
  dpos/log/eventlogs.go
  dpos/manager/proposaldispatcher.go
  test/white_box/block_utils.lua
  test/white_box/confirm_suite.lua
  test/white_box/dpos/illegal_proposals.lua
  test/white_box/dpos/normal_one_view_success.lua
  test/white_box/dpos/onduty_one_view_success.lua
  test/white_box/dpos_test_suite.lua
Labels: ct-BugFix

#734 fix update arbiters error
  dpos/manager/dposmanager.go
  dpos/manager/dposnormalhandler.go
  dpos/manager/proposaldispatcher.go
  dpos/network.go
  dpos/state/arbitrators.go
Labels: ct-BugFix

#736 fix sync from heignt 0 error
  elanet/netsync/interface.go
  elanet/netsync/manager.go
  elanet/server.go
Labels: ct-BugFix

#733 Append parameters into active net config
  common/config/params.go
  config.go
  dpos/manager/proposaldispatcher.go
Labels: ct-Refactor

#738 fix reach to H1 all arbiters not onduty error
  blockchain/blockchain.go
  mempool/blockpool.go
Labels: ct-BugFix

#739 replace 'pass by value' params with 'pass by ref'
  cmd/script/api/dposnetwork.go
  cmd/script/api/mock/dposnetwork.go
  dpos/manager/dposhandlerswitch.go
  dpos/manager/dposmanager.go
  dpos/manager/dposnormalhandler.go
  dpos/manager/dposondutyhandler.go
  dpos/manager/illegalbehaviormonitor.go
  dpos/manager/proposaldispatcher.go
  dpos/network.go
  dpos/store/eventstore_test.go
Labels: ct-Refactor

#737 restrict vote output address must be standard address
  blockchain/txvalidator.go
Labels: ct-NewFeature

#740 fix vote start height error
  blockchain/blockchain.go
  common/config/config.go
  config.go
  dpos/state/arbitrators.go
Labels: ct-BugFix

#747 fix process illegal vote error
  dpos/manager/dposnormalhandler.go
  dpos/manager/illegalbehaviormonitor.go
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#748 let arbiters handle the process special tx procedure
  blockchain/confirmvalidator.go
  blockchain/interfaces/arbitrators.go
  blockchain/mock/arbitratorsmock.go
  dpos/arbitrator.go
  dpos/manager/proposaldispatcher.go
  dpos/state/arbitrators.go
Labels: ct-Refactor

#751 remove blockflag in dpos block
  blockchain/blockchain.go
  cmd/script/api/dposmanager.go
  cmd/script/api/mock/peer.go
  cmd/script/api/txtype.go
  core/types/dposblock.go
  dpos/arbitrator.go
  dpos/manager/dposhandlerswitch.go
  dpos/manager/dposmanager.go
  elanet/netsync/manager.go
  elanet/server.go
  mempool/blockpool.go
  pow/service.go
Labels: ct-Refactor

#750 Implement side filter for side chain SPV module
  dpos/state/state.go
  elanet/bloom/txfilter.go
  elanet/filter/filter.go
  elanet/filter/sidefilter/sidefilter.go
  elanet/peer/peer.go
  elanet/server.go
Labels: ct-NewFeature

#749 producer owner receive the block reward
  dpos/state/arbitrators.go
Labels: ct-BugFix

#755 finish consensus ignore result of append confirm
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#756 remove net address not null check
  blockchain/txvalidator.go
  blockchain/txvalidator_test.go
Labels: ct-BehaviorChanges

#754 Remove interfaces/ mock/ from blockchain/ package
  blockchain/blockvalidator_test.go
  blockchain/interfaces/dposstore.go
  blockchain/interfaces/producer.go
  blockchain/ledger.go
  blockchain/mock/heightversionsmock.go
  cmd/script/api/arbitrators.go
  dpos/arbitrator.go
  dpos/manager/dposhandlerswitch.go
  dpos/manager/dposmanager.go
  dpos/manager/view.go
  dpos/manager/viewchangescountdown.go
  dpos/network.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/heightversion.go
  dpos/state/heightversion_test.go
  dpos/state/interface.go
  dpos/state/state.go
  dpos/state/state_test.go
  dpos/store/arbitratorsstore.go
  dpos/store/dbtable.go
  dpos/store/dposstore.go
  dpos/store/dposstoredata.go
  dpos/store/eventrecord.go
  dpos/store/eventstore.go
  dpos/store/eventstoreanalyzer.go
  dpos/store/interface.go
  main.go
  mempool/txpool_test.go
  pow/service.go
  pow/service_test.go
  servers/interfaces.go
Labels: ct-Refactor

#758 get onduty arbiter by height not height + 1 before h1
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/heightversion.go
  dpos/state/heightversion_test.go
  dpos/state/interface.go
Labels: ct-BugFix

#761 modify to sort arbiters by vote and public key
  dpos/state/arbitrators.go
  servers/interfaces.go
Labels: ct-BugFix

#763 Separate TxFilter Match() to confirmed and unconfirmed
  elanet/bloom/txfilter.go
  elanet/filter/filter.go
  elanet/filter/merkleblock.go
  elanet/filter/sidefilter/sidefilter.go
  elanet/filter/txtypefilter.go
  elanet/server.go
Labels: ct-NewFeature

#766 Fix config sigalton reference cause panic issue
  blockchain/confirmvalidator.go
  cmd/script/api/arbitrators.go
  common/config/config.go
  config.go
  dpos/manager/proposaldispatcher.go
  dpos/manager/viewchangescountdown.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/heightversion.go
  dpos/state/interface.go
  dpos/state/state.go
  servers/interfaces.go
Labels: ct-BugFix

#764 get dpos peers information include CRC producers
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/interface.go
  servers/interfaces.go
Labels: ct-BugFix

#767 Add PreConnectOffset parameter into chain config
  blockchain/blockchain.go
  common/config/config.go
  common/config/params.go
  common/config/template.go
  config.go
  config.json.sample
  dpos/state/arbitrators.go
Labels: ct-ConfigChanges

#770 Compatible for old version SPV clients
  elanet/filter/filter.go
  elanet/filter/merkleblock.go
  elanet/server.go
Labels: ct-NewFeature

#771 restrict crc arbiters can not be inactive
  blockchain/txvalidator.go
  dpos/state/state.go
  dpos/store/eventstoreanalyzer.go
Labels: ct-BehaviorChanges

#775 optimize the config structure and adjust default parameters
  common/config/config.go
  common/config/params.go
  config.json.sample
Labels: ct-ConfigChanges

#772 Fix server peers state inconsistent issue
  dpos/p2p/server.go
  elanet/server.go
  p2p/server/server.go
Labels: ct-BugFix

#777 add getconfirmbyheight and getconfirmbyhash restful interface
  docs/Restful_API.md
  docs/Restful_API_CN.md
  servers/httprestful/server.go
Labels: ct-RestFul

#779 add default CRCArbiters for regnet
  common/config/params.go
Labels: ct-ConfigChanges

#782 Add write message timeout for DPOS peers
  dpos/p2p/peer/peer.go
Labels: ct-BehaviorChanges

#781 Fix sending wrong block inv to SPV issue
  dpos/state/arbitrators.go
  elanet/peer/peer.go
  elanet/server.go
Labels: ct-BugFix

#786 add default parameters for config
  blockchain/blockvalidator.go
  common/config/config.go
  common/config/params.go
  config.go
  config.json.sample
  dpos/network.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/heightversion_test.go
  dpos/state/interface.go
  elanet/bloom/merkleproof.go
  elanet/pact/protocol.go
  main.go
  p2p/msg/block.go
  p2p/msg/merkleblock.go
  pow/service_test.go
Labels: ct-ConfigChanges

#787 add wirteTimeout for p2p write message
  p2p/peer/peer.go
Labels: ct-BehaviorChanges

#788 fix relay inventory error
  elanet/server.go
Labels: ct-BugFix

#789 Show BlockChain init progress on startup
  blockchain/blockchain.go
  cmd/script/api/api.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/interface.go
  glide.yaml
  log.go
  main.go
Labels: ct-NewFeature

#790 fix dead lock when return deposit
  dpos/state/state.go
Labels: ct-BugFix

#791 Move first CoinBaseTx check out of loop
  blockchain/blockvalidator.go
Labels: ct-BugFix

#792 Relay block message to SPV before H1
  elanet/server.go
Labels: ct-BugFix

#795 init currentArbitrators when new arbiters
  dpos/state/arbitrators.go
Labels: ct-BugFix

#797 Fix peer msg switch type not working issue
  elanet/server.go
  elanet/server_test.go
Labels: ct-BugFix

#798 start arbiter before initialize producer state
  main.go
Labels: ct-BugFix

#793 Relay tx inventory when a tx accepted through RPC
  servers/interfaces.go
Labels: ct-BehaviorChanges

#799 Fix unknown done peer issue
  elanet/server.go
  elanet/server_test.go
Labels: ct-BugFix

#800 add default value for config
  common/config/params.go
Labels: ct-BugFix

#805 add default value of CRCOnlyDPOSHeight and PublicDPOSHeight for RegNet
  common/config/params.go
Labels: ct-ConfigChanges

#803 modify for recover abnormal status
  cmd/script/api/mock/dposnetwork.go
  dpos/manager/dposhandlerswitch.go
  dpos/manager/dposmanager.go
  dpos/manager/proposaldispatcher.go
  dpos/network.go
Labels: ct-BugFix

#802 Update server hanlePeerMsg unit test
  elanet/server_test.go
Labels: enhancement

#808 Release v0.3.0
  blockchain/txvalidator.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/interface.go
  elanet/server.go
  servers/interfaces.go
Labels: ct-BugFix

#810 modify logic of recover abnormal status and broadcast block
  dpos/manager/dposhandlerswitch.go
  dpos/manager/dposmanager.go
  dpos/manager/dposnormalhandler.go
  dpos/manager/dposondutyhandler.go
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#783 let individual producer inactive state count by continuous absent pro…
  dpos/state/state.go
  dpos/state/state_test.go
Labels: ct-BugFix

#801 Release resources
  blockchain/chainstore.go
Labels: ct-BugFix

#809 clean block pool when a block has six confirmations
  elanet/netsync/manager.go
  mempool/blockpool.go
Labels: ct-NewFeature

#815 fix negotiate failed sometimes lead to block error
  dpos/p2p/peer/peer.go
  p2p/peer/peer.go
Labels: ct-BugFix

#818 fix send message failed error
  p2p/peer/peer.go
Labels: ct-BugFix

#819 forbit reorganize more than 6 block after DPOS is enable
  blockchain/blockchain.go
Labels: ct-BugFix

#820 Start peer message in&out after initialize
  elanet/server.go
  p2p/peer/peer.go
Labels: ct-BugFix

#824 fix recover abnormal status error
  blockchain/confirmvalidator.go
  blockchain/txvalidator.go
  dpos/arbitrator.go
  dpos/manager/dposmanager.go
  dpos/manager/proposaldispatcher.go
  main.go
Labels: ct-BugFix

#826 rename GetDposPeersInfo to GetArbiterPeersInfo
  docs/jsonrpc_apis.md
  dpos/arbitrator.go
  servers/httpjsonrpc/server.go
  servers/interfaces.go
Labels: ct-RPC

#827 fix get minority count error
  blockchain/confirmvalidator.go
  blockchain/txvalidator.go
  dpos/manager/proposaldispatcher.go
  dpos/state/arbitrators.go
Labels: ct-BugFix

#829 notify ETTransactionAccepted after append to transaction pool succeed
  mempool/txpool.go
Labels: ct-BugFix

#823 move crc reward into uniform address
  common/config/config.go
  common/config/params.go
  config.go
  dpos/state/arbitrators.go
Labels: ct-ConfigChanges
