Repository elastos/Elastos.ELA, pull requests merged in 2019-04, with the labels that each got.

#838 add go_import_path in .travis.yml
  .travis.yml
Labels: ct-BuildChanges

#839 fix write conlict of session and dpos log error
  blockchain/confirmvalidator.go
  servers/httpwebsocket/session.go
Labels: ct-BugFix

#842 modify .travis.yml
  .travis.yml
Labels: ct-BuildChanges

#837 fix data race error of eventstore and get current height
  dpos/network.go
  dpos/store/eventstore.go
Labels: ct-BugFix

#836 Set default port for seed addresses
  common/config/params.go
Labels: ct-BugFix

#828 add rpc interface to get utxo by amount
  docs/jsonrpc_apis.md
  servers/httpjsonrpc/server.go
  servers/interfaces.go
Labels: ct-RPC

#843 only recover status after CRCOnlyDPOSHeight
  dpos/manager/dposmanager.go
Labels: ct-BugFix

#845 let bad network event seialize with other dpos network events
  dpos/manager/dposmanager.go
  dpos/network.go
Labels: ct-BugFix

#848 get received fork block evidence from block pool
  mempool/blockevidence.go
Labels: ct-BugFix

#852 modify .travis.yml to compile all files
  .travis.yml
Labels: ct-BuildChanges

#853 fix dead lock of txpool error
  mempool/txpool.go
Labels: ct-BugFix

#846 sideChainPow tx does not need inputs and fee
  blockchain/txvalidator.go
  blockchain/txvalidator_test.go
  core/types/transaction.go
Labels: ct-BehaviorChanges

#857 fix recover when received same proposals error
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#858 add special tx related unit test and fix some check errors
  blockchain/confirmvalidator.go
  blockchain/confirmvalidator_test.go
  blockchain/txvalidator.go
  blockchain/txvalidator_specailtx_test.go
  blockchain/txvalidator_test.go
  dpos/manager/proposaldispatcher.go
  dpos/state/arbitratorsmock.go
Labels: ct-BugFix

#859 modify rpc interface listproducers and start time of recover
  dpos/arbitrator.go
  dpos/manager/dposmanager.go
  dpos/state/state.go
  main.go
  servers/interfaces.go
Labels: ct-BugFix

#855 Implement DPOS network hub feature
  common/config/config.go
  common/config/template.go
  config.json.sample
  dpos/manager/consensusblockcache.go
  dpos/network.go
  dpos/p2p/config.go
  dpos/p2p/hub/conn.go
  dpos/p2p/hub/hub.go
  dpos/p2p/hub/hub_test.go
  dpos/p2p/hub/log.go
  dpos/p2p/msg/version.go
  dpos/p2p/notifier_test.go
  dpos/p2p/peer/peer.go
  dpos/p2p/peer/peer_test.go
  dpos/p2p/server.go
  dpos/p2p/server_test.go
Labels: ct-ConfigChanges, ct-NewFeature

#862 add switch for http restful port and websocket port
  common/config/config.go
  common/config/template.go
  config.json.sample
  docs/config.json.md
  docs/mainnet_config.json.sample
  docs/testnet_config.json.sample
  main.go
Labels: ct-ConfigChanges

#860 Make SeedList not permanent, add PermanentPeers to config
  common/config/config.go
  elanet/interface.go
  elanet/server.go
  main.go
  p2p/server/config.go
  p2p/server/server.go
Labels: ct-ConfigChanges

#863 there should be only one special output in a tx
  blockchain/txvalidator.go
  blockchain/txvalidator_test.go
Labels: ct-BehaviorChanges

#868 do not process block for state second time if reorganized
  blockchain/blockchain.go
Labels: ct-BugFix

#867 let sidechain pow tx has high priority into a block
  pow/service.go
Labels: ct-BehaviorChanges

#870 Fix websocket server session map concurrent issue
  glide.yaml
  main.go
  servers/httpwebsocket/server.go
  servers/httpwebsocket/session.go
Labels: ct-BugFix, ct-Refactor

#872 Fix websocket conn concurrent write panic issue
  servers/httpwebsocket/server.go
  servers/httpwebsocket/session.go
Labels: ct-BugFix

#874 update the documents about config.json
  config.json.sample
  docs/config.json.md
  docs/mainnet_config.json.sample
  docs/testnet_config.json.sample
Labels: ct-ConfigChanges

#869 Implement elanet DNS service
  .gitignore
  Makefile
  elanet/dns/README.md
  elanet/dns/dns.go
  elanet/dns/dns_test.go
  elanet/dns/log.go
  elanet/dns/main/main.go
Labels: ct-NewFeature

#877 Merge branch 'upstream/release_v0.3.1' into dev
  .travis.yml
  blockchain/blockchain.go
  blockchain/confirmvalidator.go
  common/config/config.go
  common/config/params.go
  common/config/template.go
  config.json.sample
  core/types/transaction.go
  docs/config.json.md
  docs/mainnet_config.json.sample
  docs/testnet_config.json.sample
  dpos/manager/dposmanager.go
  dpos/manager/illegalbehaviormonitor.go
  dpos/state/arbitrators.go
  dpos/state/state.go
  elanet/interface.go
  elanet/netsync/manager.go
  elanet/server.go
  elanet/server_test.go
  errors/errcode.go
  errors/errcode_test.go
  glide.yaml
  main.go
  mempool/blockevidence.go
  mempool/error.go
  mempool/txpool.go
  mempool/txpool_test.go
  p2p/peer/peer.go
  p2p/peer/peer_test.go
  p2p/server/config.go
  p2p/server/server.go
  servers/httpwebsocket/server.go
  servers/httpwebsocket/session.go
  servers/interfaces.go
Labels: merge

#878 Release v0.3.1
  .travis.yml
  blockchain/blockchain.go
  blockchain/confirmvalidator.go
  common/config/config.go
  common/config/params.go
  common/config/template.go
  config.json.sample
  core/types/transaction.go
  docs/config.json.md
  docs/mainnet_config.json.sample
  docs/testnet_config.json.sample
  dpos/manager/dposmanager.go
  dpos/manager/illegalbehaviormonitor.go
  dpos/manager/proposaldispatcher.go
  dpos/state/arbitrators.go
  dpos/state/state.go
  elanet/interface.go
  elanet/netsync/manager.go
  elanet/server.go
  elanet/server_test.go
  errors/errcode.go
  errors/errcode_test.go
  glide.yaml
  main.go
  mempool/blockevidence.go
  mempool/error.go
  mempool/txpool.go
  mempool/txpool_test.go
  p2p/peer/peer.go
  p2p/server/config.go
  p2p/server/server.go
  servers/httpwebsocket/server.go
  servers/httpwebsocket/session.go
  servers/interfaces.go
Labels: merge

#890 relay illegal and inactive transactions when ETTransactionAccepted
  blockchain/txvalidator.go
  elanet/netsync/manager.go
Labels: ct-BugFix

#891 Do not disconnect peer relaying route address
  elanet/routes/routes.go
Labels: ct-BehaviorChanges

#892 Figure out self address and do not connect it
  elanet/dns/dns_test.go
  p2p/connmgr/connmanager.go
  p2p/peer/peer.go
  p2p/peer/peer_test.go
  p2p/server/server.go
Labels: ct-BehaviorChanges

#895 fix waitRecover channel may close failed error
  dpos/manager/dposmanager.go
  dpos/manager/viewchangescountdown.go
Labels: ct-BugFix

#897 Fix routes config TimeSource nil pointer issue
  main.go
Labels: ct-BugFix

#898 modify deal with inactive transaction error
  dpos/manager/dposmanager.go
  dpos/manager/proposaldispatcher.go
  dpos/manager/viewchangescountdown.go
  dpos/state/arbitrators.go
Labels: ct-BugFix

#906 panic when preconnect found next arbiters not enough
  dpos/state/arbitrators.go
Labels: ct-BehaviorChanges

#909 replace getProducers by GetActiveProducers when updateNextArbitrators
  dpos/state/arbitrators.go
  dpos/state/heightversion_test.go
  dpos/state/state.go
Labels: ct-BugFix

#900 check node public key about register and update producer txs
  blockchain/txvalidator.go
  blockchain/txvalidator_test.go
Labels: ct-BugFix

#907 broadcast block to dpos network when received higher block
  dpos/manager/dposmanager.go
Labels: ct-NewFeature

#904 Fix persist UTXOs error issue
  blockchain/chaindata.go
  blockchain/chainstore.go
Labels: ct-BugFix

#913 fix recover consensus status failed error
  config.json.sample
  dpos/manager/proposaldispatcher.go
Labels: ct-BugFix

#916 let count of special output check after H2
  blockchain/txvalidator.go
  blockchain/txvalidator_test.go
  dpos/manager/proposaldispatcher.go
Labels: ct-BehaviorChanges

#917 check timeout from PublicDposHeight when view changes
  dpos/manager/viewchangescountdown.go
Labels: ct-BugFix

#910 Merge genesis.go into params.go
  common/config/genesis.go
  common/config/genesis_test.go
  common/config/params.go
  common/config/params_test.go
Labels: ct-AddComments

#915 Set default value for DPoS tolerance time
  common/config/config.go
  common/config/params.go
  config.go
  config.json.sample
  docs/config.json.md
  dpos/arbitrator.go
  main.go
Labels: ct-BugFix

#908 Change trickle interval to speed up tx relay
  elanet/peer/peer.go
  elanet/server.go
Labels: ct-BehaviorChanges

#920 fix recover abnormal state and process InactiveArbitrators transaction error
  dpos/arbitrator.go
  dpos/manager/dposmanager.go
  dpos/network.go
  dpos/state/arbitrators.go
Labels: ct-BugFix

#923 fix create inactive arbitrator tx may sometimes failed error
  dpos/manager/consensus.go
  dpos/manager/dposhandlerswitch.go
  dpos/manager/dposmanager.go
  dpos/manager/proposaldispatcher.go
  dpos/manager/viewchangescountdown.go
Labels: ct-BugFix

#924 Degration
  dpos/manager/viewchangescountdown.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/degradation.go
  dpos/state/heightversion_test.go
  dpos/state/interface.go
  dpos/state/state.go
Labels: ct-BehaviorChanges

#925 fix coinbase related errors
  dpos/network.go
  dpos/state/arbitrators.go
  dpos/state/state.go
Labels: ct-BugFix

#926 fix check and process inatctive arbitrator transaction error
  blockchain/blockchain.go
  blockchain/confirmvalidator.go
  blockchain/confirmvalidator_test.go
  blockchain/txvalidator.go
  blockchain/txvalidator_specailtx_test.go
  blockchain/validation.go
  dpos/manager/proposaldispatcher.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/interface.go
Labels: ct-BugFix

#929 fix check inactive arbitrators payload error
  blockchain/txvalidator.go
Labels: ct-BugFix

#930 fix check side chain pow tx failed after PublicDposHeight error
  blockchain/txvalidator.go
  dpos/state/arbitrators.go
  dpos/state/arbitratorsmock.go
  dpos/state/interface.go
  mempool/txpool.go
Labels: ct-BugFix

#927 activateProducer tx does not do context checking
  blockchain/txvalidator.go
Labels: ct-BugFix
